version: '3.8'

services:
  web:
    image: nginx
    ports:
      - "8080:80"
    depends_on:
      - db
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: cuong1182004
      MYSQL_DATABASE: customer
      MYSQL_USER: root
      MYSQL_PASSWORD: cuong1182004
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  dbdata:
